version: '3.8'

services:
    peer1:
      image: p2p_app:1.0
      ports:
        - "5001:5000"
      environment:
        - PEER_ID=peer1
        - BOOTSTRAP_ADDRESS=peer2
      networks:
        - p2p-network

    peer2:
      image: p2p_app:1.0
      ports:
        - "5002:5000"
      environment:
        - PEER_ID=peer2
        - BOOTSTRAP_ADDRESS=peer1
      networks:
        - p2p-network


networks:
  p2p-network:
    driver: bridge
