version: '3.8'

services:
    peer1:
      image: p2p_app:1.3
      ports:
        - "5001:5000"
      environment:
        - PEER_ID=peer1
        - BOOTSTRAP_ADDRESS=peer2
        - PEERS=peer2,peer3,peer4,peer5
      networks:
        - p2p-network

    peer2:
      image: p2p_app:1.3
      ports:
        - "5002:5000"
      environment:
        - PEER_ID=peer2
        - BOOTSTRAP_ADDRESS=peer1
        - PEERS=peer3,peer4,peer5
      networks:
        - p2p-network

    peer3:
      image: p2p_app:1.3
      ports:
        - "5003:5000"
      environment:
        - PEER_ID=peer3
        - BOOTSTRAP_ADDRESS=peer1
        - PEERS=peer4,peer5
      networks:
        - p2p-network

    peer4:
      image: p2p_app:1.3
      ports:
        - "5004:5000"
      environment:
        - PEER_ID=peer4
        - BOOTSTRAP_ADDRESS=peer1
        - PEERS=peer5
      networks:
        - p2p-network

    peer5:
      image: p2p_app:1.3
      ports:
        - "5005:5000"
      environment:
        - PEER_ID=peer5
        - BOOTSTRAP_ADDRESS=peer1
        - PEERS=
      networks:
        - p2p-network

networks:
  p2p-network:
    driver: bridge
